items:
    - Acacia_Boat
    - Acacia_Button
    - Acacia_Door
    - Acacia_fence
    - Acacia_fence_gate
    - Acacia_leaves
    - Acacia_log
    - Acacia_planks
    - Acacia_pressure_plate
    - Acacia_sapling
    - Acacia_sign
    - Acacia_slab
    - Acacia_stairs
    - Acacia_trapdoor
    - Acacia_wood
    - Activator_rail
    - Allium
    - Ancient_debris
    - Andesite
    - Andesite_slab
    - Andesite_stairs
    - Andesite_wall
    - Anvil
    - Apple
    - Armor_stand
    - Arrow
    - Azure_bluet
    - Baked_potato
    - Bamboo
    - Barrel
    - Basalt
    - Beacon
    - Beetroot
    - Beetroot_seeds
    - Beetroot_soup
    - Bell
    - Birch_boat
    - Birch_button
    - Birch_fence
    - Birch_fence_gate
    - Birch_leaves
    - Birch_log
    - Birch_planks
    - Birch_pressure_plate
    - Birch_sign
    - Birch_slab
    - Birch_stairs
    - Birch_trapdoor
    - Birch_wood
    - Black_banner
    - black_bed
    - black_carpet
    - black_concrete
    - black_concrete_powder
    - Black_dye
    - black_glazed_terracotta
    - black_stained_glass_pane
    - black_stained_glass
    - black_terracotta
    - black_wool
    - blackstone
    - polished_blackstone_bricks
    - blackstone_slab
    - blackstone_stairs
    - blackstone_wall
    - blast_furnace
    - Blaze_powder
    - Blaze_rod
    - coal_block
    - diamond_block
    - emerald_block
    - gold_block
    - iron_block
    - netherite_block
    - quartz_block
    - redstone_block
    - blue_banner
    - blue_bed
    - blue_carpet
    - blue_concrete
    - blue_concrete_powder
    - Blue_dye
    - blue_glazed_terracotta
    - blue_ice
    - blue_orchid
    - blue_shulker_box
    - blue_stained_glass
    - blue_stained_glass_pane
    - blue_terracotta
    - blue_wool
    - Bone
    - bone_block
    - Bone_meal
    - Book
    - writable_book
    - Bookshelf
    - Bow
    - Bowl
    - Bread
    - brewing_stand
    - Brick
    - brick_slab
    - brick_stairs
    - brick_wall
    - bricks
    - brown_banner
    - brown_bed
    - brown_carpet
    - Brown_concrete
    - Brown_concrete_powder
    - Brown_dye
    - Brown_glazed_terracotta
    - Brown_mushroom
    - Brown_mushroom_block
    - Brown_shulker_box
    - Brown_stained_glass
    - Brown_stained_glass_pane
    - Brown_terracotta
    - Brown_wool
    - Bubble_coral
    - Bubble_coral_block
    - Bubble_coral_fan
    - Bucket
    - cod_bucket
    - pufferfish_bucket
    - salmon_bucket
    - tropical_fish_bucket
    - Carrot
    - Birch_Door
    - Birch_sapling
    - Cactus
    - cake
    - Campfire
    - Carrot_on_a_stick
    - Cartography_table
    - carved_pumpkin
    - cauldron
    - Charcoal
    - chest
    - chipped_anvil
    - chiseled_nether_bricks
    - chiseled_polished_blackstone
    - chiseled_quartz_block
    - chiseled_red_sandstone
    - Chiseled_sandstone
    - Chiseled_stone_bricks
    - Clay
    - Clay_ball
    - Clock
    - Coal
    - Coal_ore
    - Coarse_dirt
    - Cobblestone
    - Cobblestone_slab
    - Cobblestone_stairs
    - Cobblestone_wall
    - Compass
    - Composter
    - Cooked_chicken
    - Cooked_cod
    - Cooked_mutton
    - Cooked_porkchop
    - Cooked_rabbit
    - Cooked_salmon
    - Cookie
    - Cornflower
    - Cracked_nether_bricks
    - Cracked_polished_blackstone_bricks
    - Cracked_stone_bricks
    - Crafting_table
    - Crimson_button
    - crimson_door
    - Crimson_fence
    - Crimson_fence_gate
    - Crimson_fungus
    - Crimson_hyphae
    - Crimson_nylium
    - Crimson_planks
    - Crimson_pressure_plate
    - Crimson_roots
    - Crimson_sign
    - Crimson_slab
    - Crimson_stairs
    - Crimson_stem
    - Crimson_trapdoor
    - Crossbow
    - crying_obsidian
    - Cut_red_sandstone
    - Cut_red_sandstone_slab
    - Cut_sandstone
    - cut_sandstone_slab
    - Cyan_banner
    - cyan_bed
    - cyan_carpet
    - cyan_concrete
    - cyan_concrete_powder
    - Cyan_dye
    - cyan_glazed_terracotta
    - cyan_shulker_box
    - cyan_stained_glass
    - cyan_stained_glass_pane
    - cyan_terracotta
    - damaged_anvil
    - dandelion
    - Dark_oak_boat
    - dark_oak_button
    - dark_oak_door
    - dark_oak_fence
    - dark_oak_fence_gate
    - dark_oak_leaves
    - dark_oak_log
    - dark_oak_planks
    - dark_oak_pressure_plate
    - dark_oak_sapling
    - dark_oak_sign
    - dark_oak_slab
    - dark_oak_stairs
    - dark_oak_trapdoor
    - dark_oak_wood
    - dark_prismarine
    - dark_prismarine_slab
    - dark_prismarine_stairs
    - daylight_detector
    - dead_bush
    - detector_rail
    - Diamond
    - Diamond_axe
    - Diamond_boots
    - Diamond_chestplate
    - Diamond_helmet
    - Diamond_hoe
    - Diamond_horse_armor
    - Diamond_leggings
    - diamond_ore
    - Diamond_pickaxe
    - Diamond_shovel
    - Diamond_sword
    - diorite
    - diorite_slab
    - diorite_wall
    - dirt
    - dispenser
    - Dried_kelp
    - dried_kelp_block
    - dropper
    - Egg
    - Emerald
    - emerald_ore
    - map
    - enchanting_table
    - End_crystal
    - ender_chest
    - Ender_pearl
    - ender_eye
    - Feather
    - Fermented_spider_eye
    - fern
    - Fire_charge
    - Firework_rocket
    - Firework_star
    - Fishing_rod
    - fletching_table
    - Flint
    - Flint_and_steel
    - flower_pot
    - furnace
    - Ghast_tear
    - gilded_blackstone
    - glass
    - Glass_bottle
    - glass_pane
    - Glistering_melon_slice
    - glowstone
    - Glowstone_dust
    - Gold_ingot
    - Gold_nugget
    - gold_ore
    - Golden_apple
    - Golden_axe
    - Golden_boots
    - Golden_carrot
    - Golden_chestplate
    - Golden_helmet
    - Golden_hoe
    - Golden_horse_armor
    - Golden_leggings
    - Golden_pickaxe
    - Golden_shovel
    - Golden_sword
    - granite
    - granite_slab
    - granite_stairs
    - granite_wall
    - grass
    - gravel
    - gray_banner
    - gray_bed
    - gray_carpet
    - gray_concrete
    - gray_concrete_powder
    - Gray_dye
    - gray_glazed_terracotta
    - gray_shulker_box
    - gray_stained_glass
    - gray_stained_glass_pane
    - gray_terracotta
    - gray_wool
    - green_banner
    - green_bed
    - green_carpet
    - green_concrete
    - green_concrete_powder
    - Green_dye
    - green_glazed_terracotta
    - green_shulker_box
    - green_stained_glass
    - green_stained_glass_pane
    - green_terracotta
    - green_wool
    - grindstone
    - Gunpowder
    - hay_block
    - heavy_weighted_pressure_plate
    - honey_block
    - Honey_bottle
    - Honeycomb
    - honeycomb_block
    - hopper
    - Ink_sac
    - Iron_axe
    - iron_bars
    - Iron_boots
    - Iron_chestplate
    - iron_door
    - Iron_helmet
    - Iron_hoe
    - Iron_horse_armor
    - Iron_ingot
    - Iron_leggings
    - Iron_nugget
    - iron_ore
    - Iron_pickaxe
    - Iron_shovel
    - Iron_sword
    - iron_trapdoor
    - Item_frame
    - jack_o_lantern
    - jukebox
    - Jungle_boat
    - jungle_button
    - jungle_door
    - jungle_fence
    - jungle_fence_gate
    - jungle_leaves
    - jungle_log
    - jungle_planks
    - jungle_pressure_plate
    - jungle_sapling
    - jungle_sign
    - jungle_stairs
    - jungle_trapdoor
    - jungle_wood
    - kelp
    - ladder
    - lantern
    - Lapis_lazuli
    - lapis_block
    - lapis_ore
    - Lava_bucket
    - Lead
    - Leather
    - Leather_boots
    - Leather_helmet
    - Leather_horse_armor
    - Leather_leggings
    - Leather_chestplate
    - lectern
    - lever
    - light_blue_banner
    - light_blue_bed
    - light_blue_carpet
    - light_blue_concrete
    - light_blue_concrete_powder
    - Light_blue_dye
    - light_blue_glazed_terracotta
    - light_blue_shulker_box
    - light_blue_stained_glass
    - light_blue_stained_glass_pane
    - light_blue_terracotta
    - light_blue_wool
    - light_gray_banner
    - light_gray_bed
    - light_gray_carpet
    - light_gray_concrete
    - light_gray_concrete_powder
    - Light_gray_dye
    - light_gray_glazed_terracotta
    - light_gray_shulker_box
    - light_gray_stained_glass
    - light_gray_stained_glass_pane
    - light_gray_terracotta
    - light_gray_wool
    - light_weighted_pressure_plate
    - lilac
    - lily_of_the_valley
    - lily_pad
    - lime_banner
    - lime_bed
    - lime_carpet
    - lime_concrete
    - lime_concrete_powder
    - Lime_dye
    - Lime_glazed_terracotta
    - Lime_shulker_box
    - Lime_stained_glass
    - Lime_stained_glass_pane
    - Lime_wool
    - lodestone
    - loom
    - magenta_banner
    - magenta_bed
    - magenta_carpet
    - magenta_concrete
    - magenta_concrete_powder
    - Magenta_dye
    - magenta_glazed_terracotta
    - magenta_shulker_box
    - magenta_stained_glass
    - magenta_stained_glass_pane
    - magenta_terracotta
    - magenta_wool
    - magma_block
    - Magma_cream
    - melon
    - Melon_seeds
    - Milk_bucket
    - Minecart
    - chest_Minecart
    - furnace_Minecart
    - hopper_Minecart
    - tnt_Minecart
    - mossy_cobblestone
    - mossy_cobblestone_slab
    - mossy_cobblestone_stairs
    - mossy_cobblestone_wall
    - mossy_stone_bricks
    - mossy_stone_brick_slab
    - mossy_stone_brick_stairs
    - mossy_stone_brick_wall
    - mushroom_stem
    - Mushroom_stew
    - mycelium
    - Name_tag
    - Nautilus_shell
    - Nether_brick
    - nether_brick_fence
    - nether_brick_slab
    - nether_brick_stairs
    - nether_brick_wall
    - nether_bricks
    - nether_gold_ore
    - quartz
    - nether_quartz_ore
    - nether_sprouts
    - Nether_star
    - nether_wart
    - nether_wart_block
    - netherrack
    - note_block
    - Oak_boat
    - oak_button
    - oak_door
    - oak_fence
    - oak_fence_gate
    - oak_leaves
    - oak_log
    - oak_planks
    - oak_pressure_plate
    - oak_sapling
    - oak_sign
    - oak_slab
    - oak_stairs
    - oak_trapdoor
    - oak_wood
    - observer
    - obsidian
    - orange_banner
    - orange_carpet
    - orange_concrete
    - orange_concrete_powder
    - Orange_dye
    - orange_glazed_terracotta
    - orange_shulker_box
    - orange_stained_glass
    - orange_stained_glass_pane
    - orange_terracotta
    - orange_tulip
    - orange_wool
    - oxeye_daisy
    - Painting
    - Paper
    - peony
    - pink_banner
    - pink_carpet
    - pink_concrete
    - pink_concrete_powder
    - Pink_dye
    - pink_glazed_terracotta
    - pink_shulker_box
    - pink_stained_glass
    - pink_stained_glass_pane
    - pink_terracotta
    - pink_tulip
    - pink_wool
    - piston
    - podzol
    - Poisonous_potato
    - polished_andesite
    - polished_andesite_slab
    - polished_andesite_stairs
    - polished_basalt
    - polished_blackstone
    - polished_blackstone_brick_slab
    - polished_blackstone_brick_stairs
    - polished_blackstone_brick_wall
    - polished_blackstone_bricks
    - polished_blackstone_button
    - polished_blackstone_pressure_plate
    - polished_blackstone_slab
    - polished_blackstone_stairs
    - polished_blackstone_wall
    - polished_diorite
    - polished_diorite_slab
    - polished_diorite_stairs
    - polished_granite
    - polished_granite_slab
    - polished_granite_stairs
    - Popped_chorus_fruit
    - poppy
    - potatoes
    - powered_rail
    - Pufferfish
    - pumpkin
    - Pumpkin_pie
    - Pumpkin_seeds
    - purple_banner
    - purple_carpet
    - purple_concrete
    - purple_concrete_powder
    - Purple_dye
    - purple_glazed_terracotta
    - purple_shulker_box
    - purple_stained_glass
    - purple_stained_glass_pane
    - purple_terracotta
    - purple_wool
    - Quartz_block
    - Quartz_pillar
    - Quartz_slab
    - Quartz_stairs
    - Rabbit_hide
    - Rabbit_stew
    - rabbit_foot
    - Rail
    - beef
    - chicken
    - cod
    - mutton
    - porkchop
    - rabbit
    - salmon
    - Red_banner
    - Red_bed
    - Red_carpet
    - Red_concrete
    - Red_concrete_powder
    - Red_dye
    - Red_glazed_terracotta
    - Red_mushroom
    - Red_mushroom_block
    - Red_nether_brick_slab
    - Red_nether_brick_stairs
    - Red_nether_brick_wall
    - Red_nether_bricks
    - Red_sand
    - Red_sandstone
    - Red_sandstone_slab
    - Red_sandstone_stairs
    - Red_sandstone_wall
    - Red_shulker_box
    - Red_stained_glass
    - Red_stained_glass_pane
    - Red_terracotta
    - Red_tulip
    - Red_wool
    - Redstone
    - Redstone_Block
    - repeater
    - Redstone_torch
    - Respawn_anchor
    - Rose_bush
    - Rotten_flesh
    - Sand
    - Sandstone
    - Sandstone_slab
    - Sandstone_stairs
    - Sandstone_wall
    - Scaffolding
    - Sea_pickle
    - Seagrass
    - shears
    - shield
    - Shroomlight
    - Slime_block
    - slime_ball
    - Smithing_table
    - Smoker
    - Smooth_quartz
    - Smooth_quartz_slab
    - Smooth_quartz_stairs
    - Smooth_red_sandstone
    - Smooth_red_sandstone_slab
    - Smooth_red_sandstone_stairs
    - Smooth_sandstone
    - Smooth_sandstone_slab
    - Smooth_sandstone_stairs
    - Smooth_stone
    - Smooth_stone_slab
    - Snow
    - Snow_block
    - Snowball
    - Soul_campfire
    - Soul_lantern
    - Soul_sand
    - Soul_soil
    - Soul_torch
    - spectral_arrow
    - spider_eye
    - Spruce_boat
    - Spruce_button
    - Spruce_door
    - Spruce_fence
    - Spruce_fence_gate
    - Spruce_leaves
    - Spruce_log
    - Spruce_planks
    - Spruce_pressure_plate
    - Spruce_sapling
    - Spruce_sign
    - Spruce_stairs
    - Spruce_trapdoor
    - Spruce_wood
    - cooked_beef
    - stick
    - Sticky_piston
    - Stone
    - stone_axe
    - Stone_brick_slab
    - Stone_brick_stairs
    - Stone_brick_wall
    - Stone_bricks
    - Stone_button
    - stone_hoe
    - stone_pickaxe
    - Stone_pressure_plate
    - stone_shovel
    - Stone_slab
    - Stone_stairs
    - stone_sword
    - Stonecutter
    - String
    - Stripped_acacia_log
    - Stripped_acacia_wood
    - Stripped_birch_log
    - Stripped_birch_wood
    - Stripped_crimson_hyphae
    - Stripped_crimson_stem
    - Stripped_dark_oak_log
    - Stripped_dark_oak_wood
    - Stripped_jungle_log
    - Stripped_jungle_wood
    - Stripped_oak_log
    - Stripped_oak_wood
    - Stripped_spruce_log
    - Stripped_spruce_wood
    - Stripped_warped_hyphae
    - Stripped_warped_stem
    - sugar
    - Sugar_cane
    - Sunflower
    - suspicious_stew
    - Sweet_berries
    - Target
    - Terracotta
    - TNT
    - Torch
    - Trapped_chest
    - Tripwire_hook
    - tropical_fish
    - Twisting_vines
    - Vine
    - Warped_button
    - Warped_door
    - Warped_fence
    - Warped_fence_gate
    - Warped_fungus
    - Warped_hyphae
    - Warped_nylium
    - Warped_planks
    - Warped_pressure_plate
    - Warped_roots
    - Warped_sign
    - Warped_slab
    - Warped_stairs
    - Warped_stem
    - Warped_trapdoor
    - Warped_wart_block
    - Water_bucket
    - Weeping_vines
    - Wheat
    - Wheat_seeds
    - White_banner
    - White_bed
    - White_carpet
    - White_concrete
    - White_concrete_powder
    - white_dye
    - White_glazed_terracotta
    - White_shulker_box
    - White_stained_glass
    - White_stained_glass_pane
    - White_terracotta
    - White_tulip
    - White_wool
    - wooden_axe
    - wooden_hoe
    - wooden_pickaxe
    - wooden_shovel
    - wooden_sword
    - Yellow_banner
    - Yellow_bed
    - Yellow_carpet
    - Yellow_concrete
    - Yellow_concrete_powder
    - yellow_dye
    - Yellow_glazed_terracotta
    - Yellow_shulker_box
    - Yellow_stained_glass
    - Yellow_stained_glass_pane
    - Yellow_terracotta
    - Yellow_wool
    - Cocoa_beans