name: FindTheItem
version: 0.0.1
author: action35
main: com.action35.findtheitem.Main
api-version: 1.16
api: []
commands:
  join:
    description: Join the fun!
    usage: /join
  leave:
    description: Stop playing!
    usage: /leave
  startgame:
    description: Start the game!
    usage: /startgame
  stopgame:
    description: Stop the game!
    usage: /stopgame